## create product 

POST http://localhost:3000/products
Content-Type : application/json

{
    "name" :"product three" , 
    "slug" : "product_three",
    "description" : "this is the description for product three ",
    "price" : 120,
    "categoryId" : "5fa39d22-e528-4672-a462-3859b8993987"
}