## get  all products
GET http://localhost:3000/products?




## get one products
GET http://localhost:3000/products/c7747af7-192f-469c-bc25-7a7fcce1137a



## get products by category id 
GET http://localhost:3000/products/category/31a9a5d8-7383-4bbf-ad1e-ad5f4364e896