


# update user by id 

PATCH http://localhost:3000/users/742e7908-3c86-46dd-b5b3-dc46255e9388
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NDJlNzkwOC0zYzg2LTQ2ZGQtYjViMy1kYzQ2MjU1ZTkzODgiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc3MjY1MzE2NywiZXhwIjoxNzcyNzM5NTY3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.yrj0w7nc7RHzYXCBzib8mwiPsH2JE9m1GrZRdScfqmM
{
    "firstName" : "updated first name",
    "lastName" : "last name",
    "email"  : "o@gmail.com"
}