## sign in new user 

POST http://localhost:3000/auth/signup
Content-Type  : application/json

{
    "firstName" : "semo",
    "lastName" : "shakerr",
    "email" : "shakerosama277@gmail.com",
    "password" : "Password1!",
    "gender" : "male",
    "age" : 17,
    "governorate" : "cairo"

}